# Generated by Django 5.1.2 on 2024-10-19 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_delete_productline'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_path',
            field=models.TextField(default='no_image.jpg'),
        ),
    ]
