# Generated by Django 5.1.2 on 2024-10-19 21:33

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_image_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_path',
        ),
        migrations.AddField(
            model_name='product',
            name='imgae',
            field=models.ImageField(default='products/default.jpg', upload_to=products.models.upload_to, verbose_name='image'),
        ),
    ]
