# Generated by Django 5.1.2 on 2024-10-20 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_image_path_product_imgae'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='imgae',
            new_name='image',
        ),
    ]
