# Generated by Django 5.1.2 on 2024-10-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_imgae_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='#3498db', max_length=7),
        ),
    ]
