# Generated by Django 5.1.2 on 2024-10-20 14:10

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_category_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='categories/default.jpg', upload_to=products.models.upload, verbose_name='image'),
        ),
    ]
