# Generated by Django 5.1.2 on 2024-10-20 21:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=3, verbose_name='price'),
        ),
    ]
